<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Accounting extends Seeder
{
    public function run()
    {
        $data = [
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1210',
                'name'          => 'Gedung',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1230',
                'name'          => 'Akm. Penyusutan - Gedung',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1310',
                'name'          => 'Renovasi Gedung',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1330',
                'name'          => 'Akm. Penyusutan Renovasi Gedung',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1410',
                'name'          => 'Asset Mesin dan Peralatan',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1430',
                'name'          => 'Akm. Penyusutan Mesin dan Peralatan',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1510',
                'name'          => 'Mobil',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1530',
                'name'          => 'Akm. Penyusutan Mobil',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1610',
                'name'          => 'Motor / Sepeda',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1630',
                'name'          => 'Akm Penyusutan Motor / Sepeda',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1710',
                'name'          => 'Furniture',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1730',
                'name'          => 'Akm. Penyusutan Furniture',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1810',
                'name'          => 'Komputer',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1231.1830',
                'name'          => 'Akm. Penyusutan Komputer',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1232.1110',
                'name'          => 'Program Komputer',
                'account_sign'  => 'N',
                'description'   => 'Intangible Asset',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '1232.1130',
                'name'          => 'Akm. Penyusutan Program Komputer',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1110',
                'name'          => 'Biaya Penyusutan Gedung',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1115',
                'name'          => 'Biaya Penyusutan Renovasi Gedung',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1120',
                'name'          => 'Biaya Penyusutan Mobil',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1125',
                'name'          => 'Biaya Penyusutan Motor / Sepeda',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1130',
                'name'          => 'Biaya Penyusutan Furniture',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1135',
                'name'          => 'Biaya Penyusutan Komputer',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6810.1140',
                'name'          => 'Biaya Penyusutan Mesin dan Peralatan',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '6820.1110',
                'name'          => 'Biaya Amortisasi Program Komputer',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '7100.1610',
                'name'          => 'Laba Penjualan Aktiva Tetap',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '7100.1620',
                'name'          => 'Laba Penjualan COP',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '7200.1610',
                'name'          => 'Rugi Penjualan Aktiva Tetap',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '7200.1750',
                'name'          => 'Rugi Penghapusan Asset Perusahaan',
                'account_sign'  => 'N',
                'description'   => '',
            ],
            [
                'created_by'    => 1,
                'updated_by'    => 1,
                'value'         => '7900.1050',
                'name'          => 'Perantara Penjualan Asset',
                'account_sign'  => 'N',
                'description'   => '',
            ],
        ];

        $this->db->table('md_account')->insertBatch($data);
    }
}
